# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9046b4ae0ccf1f2529f7e3e035689b6efd9e3337c6fa0fec6776882397725c00a5023bad2bd3ad2034f1e27c1c8fd158636edcc6f847ca87ff42303c8e5ee7f6

test:
  secret_key_base: 0ce75ac56b406c07e4a9317112fb56b61e7cb71425427869a3a8aaffa9737f1fd6b068c7734aca9c45637cd5b49c9f669e072385881db1b56653c9357fdcd042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
